// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD8ki8kJg9S5Nzk5GyG8HPcVJpE0yqmYrA',
    appId: '1:587828933428:web:d98245fbbd25063c442b61',
    messagingSenderId: '587828933428',
    projectId: 'chatting-4d32a',
    authDomain: 'chatting-4d32a.firebaseapp.com',
    storageBucket: 'chatting-4d32a.appspot.com',
    measurementId: 'G-XD03XD87VN',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBpcJewYmGhX5I-Xj8m5f1WWqaTl_kockQ',
    appId: '1:587828933428:android:da2525aa38af2ea2442b61',
    messagingSenderId: '587828933428',
    projectId: 'chatting-4d32a',
    storageBucket: 'chatting-4d32a.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDrE_xCyTWpwPhW2OLvR6ibjG8nwo16z7M',
    appId: '1:587828933428:ios:ec0b5f3da61713cd442b61',
    messagingSenderId: '587828933428',
    projectId: 'chatting-4d32a',
    storageBucket: 'chatting-4d32a.appspot.com',
    iosBundleId: 'com.example.chatting',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDrE_xCyTWpwPhW2OLvR6ibjG8nwo16z7M',
    appId: '1:587828933428:ios:ec0b5f3da61713cd442b61',
    messagingSenderId: '587828933428',
    projectId: 'chatting-4d32a',
    storageBucket: 'chatting-4d32a.appspot.com',
    iosBundleId: 'com.example.chatting',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyD8ki8kJg9S5Nzk5GyG8HPcVJpE0yqmYrA',
    appId: '1:587828933428:web:9fdbca88178234c0442b61',
    messagingSenderId: '587828933428',
    projectId: 'chatting-4d32a',
    authDomain: 'chatting-4d32a.firebaseapp.com',
    storageBucket: 'chatting-4d32a.appspot.com',
    measurementId: 'G-8GTF43VD9X',
  );
}
